workflows:
  jufa:
    name: Jufa Workflow
    max_build_duration: 10
    environment:
      groups:
        - keystore_credentials # <-- (Includes FCI_KEYSTORE, FCI_KEYSTORE_PASSWORD, FCI_KEY_PASSWORD, FCI_KEY_ALIAS)
        - google_play # <-- (Includes GCLOUD_SERVICE_ACCOUNT_CREDENTIALS)
        - discord
      vars:
        FCI_KEYSTORE_PATH: /tmp/keystore.keystore
        PACKAGE_NAME: 'de.schultek.jufa'
        GOOGLE_PLAY_TRACK: 'alpha'
      flutter: stable
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods
        - $FLUTTER_ROOT/.pub-cache
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
      cancel_previous_builds: true
    scripts:
      - name: Set up key properties
        script: |
          echo $FCI_KEYSTORE | base64 --decode > /tmp/keystore.keystore
          cat >> "$FCI_BUILD_DIR/android/key.properties" <<EOF
          storePassword=$FCI_KEYSTORE_PASSWORD
          keyPassword=$FCI_KEY_PASSWORD
          keyAlias=$FCI_KEY_ALIAS
          storeFile=/tmp/keystore.keystore
          EOF        
      - |
        echo "flutter.sdk=$HOME/programs/flutter" > "$FCI_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
          flutter pub get
      - name: Check Formatting
        script: flutter format --dry-run --set-exit-if-changed -l 120
      - name: Flutter analyze
        script: flutter analyze
      - name: Build APK with Flutter
        script: |
          flutter build apk --release --build-number=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK") + 1))
    artifacts:
      - build/**/outputs/apk/**/*.apk
      - build/**/outputs/bundle/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      scripts:
      - name: Discord notification
        script: |
          set -ex
          APP_LINK=$(echo $FCI_ARTIFACT_LINKS | jq -r '.[] | select(.name=="app.apk") | .url')
        
          # Get first 7 digits of commit number
          COMMIT=$(echo "${FCI_COMMIT}" | sed 's/^\(........\).*/\1/;q')
          # Get commit message
          COMMIT_MESSAGE=$(git log --format=%B -n 1 $FCI_COMMIT)
          # Get commit author
          AUTHOR=$(git show -s --format='%ae' $FCI_COMMIT)
          curl -H "Content-Type: multipart/form-data" \
          -F 'payload_json={"username" : "Codemagic", "content": "**Commit:** `'"$COMMIT"'`\n\n**Commit message:** '"$COMMIT_MESSAGE"'\n\n**Branch:** '"$FCI_BRANCH"'\n\n**Author:** '"$AUTHOR"'\n\n**Artifacts: **\n\n'"$APP_LINK"'\n\n"}' \
          $WEBHOOK_URL
      email:
        recipients:
          - kilian@4xschulte.de
