include: package:lints/recommended.yaml

analyzer:
  exclude:
    - lib/**.g.dart
  strong-mode:
    implicit-casts: false
    implicit-dynamic: true

linter:
  rules:
    prefer_relative_imports: true
    prefer_single_quotes: true
    avoid_print: false # TODO remove in production