name: backend
description: A server app using the shelf package and Docker.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  analyzer: ^3.4.1
  api_agent: ^0.4.0
  build: ^2.2.1
  firebase_admin:
    git:
      url: https://github.com/schultek/firebase_admin.git
      ref: feat/firebase-apis
  functions_framework: ^0.4.1
  shared:
    path: ../shared
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  source_gen: ^1.2.1
  yaml: ^3.1.0
  yaml_writer: ^1.0.1

dev_dependencies:
  build_runner: ^2.1.8
  functions_framework_builder: ^0.4.5
  http: ^0.13.0
  lints: ^1.0.0
  test_process: ^2.0.0
  test: ^1.15.0
