# flutter pub run build_runner watch --delete-conflicting-outputs
# flutter pub run build_runner build --delete-conflicting-outputs
targets:
  $default:
    builders:
      dart_mappable_builder:
        generate_for:
          - lib/main.dart
        options:
          caseStyle: camelCase
          enumCaseStyle: camelCase
