on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy_app.yml'
      - 'app/**'

name: Build and Deploy App

jobs:
  deploy_android:
    name: Deploy Android App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Cache Flutter Dependencies
        uses: actions/cache@v1
        with:
          path: /opt/hostedtoolcache/flutter
          key: ubuntu-latest-flutter

      - name: Setup Flutter
        uses: subosito/flutter-action@v1

      - name: Run Flutter Doctor
        run: flutter doctor

      - name: Write Google-Services File
        run: 'echo "$GOOGLE_SERVICES" > app/android/app/google-services.json'
        shell: bash
        env:
          GOOGLE_SERVICES: ${{ secrets.ANDROID_GOOGLE_SERVICES }}

      - name: Configure Keystore
        run: |
          echo "$ANDROID_SIGNING_KEY" | base64 --decode > app/upload-keystore.jks
          echo "storeFile=upload-keystore.jks" >> key.properties
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> key.properties
          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> key.properties
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> key.properties
        env:
          ANDROID_SIGNING_KEY: ${{ secrets.ANDROID_SIGNING_KEY }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
        working-directory: app/android

      - name: Build Android App
        run: |
          cd app
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
          flutter build appbundle --no-sound-null-safety

      - name: Write ServiceAccountKey File
        run: 'echo "$SERVICE_ACCOUNT_KEY" > app/android/serviceAccountKey.json'
        shell: bash
        env:
          SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}

      - name: Upload to Play Console
        run: |
          cd app/android
          fastlane upload

  deploy_ios:
    name: Deploy IOS App
    runs-on: macOS-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Cache Flutter Dependencies
        uses: actions/cache@v1
        with:
          path: /Users/runner/hostedtoolcache/flutter
          key: macos-latest-flutter

      - name: Setup Flutter
        uses: subosito/flutter-action@v1

      - name: Run Flutter Doctor
        run: |
          flutter doctor
          xcodebuild -version

      - name: Write Google-Services File
        run: 'echo "$GOOGLE_SERVICES" > app/ios/Runner/GoogleService-Info.plist'
        shell: bash
        env:
          GOOGLE_SERVICES: ${{ secrets.IOS_GOOGLE_SERVICES }}

      - name: Import CodeSign Certificates
        uses: Apple-Actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.CERTIFICATES_FILE_BASE64 }}
          p12-password: ${{ secrets.CERTIFICATES_PASSWORD }}

      - name: Download Provisioning Profiles
        uses: Apple-Actions/download-provisioning-profiles@v1
        with:
          bundle-id: de.schultek.jufa
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}

      - name: Build IOS App
        run: |
          cd app
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
          flutter build ipa --no-sound-null-safety --export-options-plist=ios/ExportOptions.plist

      - name: Upload to TestFlight
        uses: Apple-Actions/upload-testflight-build@master
        with:
          app-path: app/build/ios/ipa/jufa.ipa
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}